name: test

on: 
    push: 
        branches:
          - main
      

jobs:
    job-1:
        runs-on: ubuntu-22.04
        steps:
          - run: "echo Test"
          - run: "echo job one test"
            
    job-2:
        runs-on: ubuntu-22.04
        steps:
          - run: "echo Test form job 2 "
          - run: "echo job two test "