name: test

on: 
    push: 
        branches:
          - main
      

jobs:
   build:
        runs-on: ubuntu-latest

        env:
            PORT: ${{secrets.PORT}}

        strategy:
          matrix:
                node-version: [14.x, 16.x, 18.x]
        steps:
         - uses: actions/checkout@v6 
         - uses: actions/setup-node@v6
           with:
             node-version: ${{matrix.node-version}}

         - run: 'echo building application'    
         - run: npm install
         - run: npm run build  
           
   test:
    runs-on: ubuntu-latest

    strategy:
          matrix:
                node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@6
        with:
            node-version: ${{matrix.node-version}}

      - run: npm install
      - run: npm test      
